# -*- coding: utf-8 -*-
"""SparkDay2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QlkRg1CAkOZ2g-B8ZVdjo2jMGsLFvEPc
"""

print("Hello")

pip install pyspark

rdd1=sc.parallelize(['a1','a2'])

from pyspark import SparkConf,SparkContext

conf=SparkConf().setAppName("demo").setMaster("local")

sc=SparkContext(conf=conf)

#Create RDD Transform
rdd1=sc.parallelize(['a1','a2'])

# @title Default title text
#Action on RDD
rdd1.collect()

from pyspark.sql import SparkSession
spark=SparkSession.builder.getOrCreate()

#Create a DF
df=spark.createDataFrame([('a1','a2')])

df.show()

